### ISSUE TITLE
Paging does not work with HAPI FHIR Server

### ISSUE THREAD

**Issue by ManuelB** [SAP/openui5-fhir#332]
**Describe the bug**
Paging with Hapi FHIR Server is not working. 

**To Reproduce**

In case of bugs:
1. Go to https://sap-samples.github.io/openui5-fhir-sample-app/#/patients
2. Click on more

**Expected behavior**
System should load more patients

**Actually**
Nothing happens (hapi fhir server sends an error but this is not visible in the frontend.)

![Bildschirmfoto von 2022-05-14 21-22-00](https://user-images.githubusercontent.com/457641/168445633-f55ddefe-0905-4016-a8d6-1ece8e9ececb.png)

**Workaround**
For the moment we patched the FHIRListBinding in Our Component.js:
https://github.com/med-united/care.med-united.health/blob/main/webapp/medunited/care/Component.js#L64

**Comment by AmirthavalliG** [comment]
@ManuelB : This issue is now fixed with 2.3.2. We still have the default behaviour which can be overridden to avoid the next link from not being processed. You can find more details here  Pagination Requests https://sap.github.io/openui5-fhir/tutorial-4%20Request%20Handling.html. Apologies for the delay
